--[[
* GENERATED by luajit tools/gentables.lua.  Do not edit; regenerate.
*
* Enmity rules that aren't a single action's base value: buffs,
* conditional bonuses, and gear.  Curated in tools/tables/horizon.lua;
* every rule is preceded by the quotes that justify it and where they
* are, checked against the sources at generation.
*
* Sources
*   lsb      LandSandBoat e81c8864748253105f9e6c36ab519c24eb01256f (2026-09-06)
*   horizon  HorizonXI wiki snapshots at the revisions cited
*
* Trust
*   era      measured in era (Kaeko), or documented as Horizon's own value
*   lsb      LandSandBoat's value with nothing to corroborate it
*   unknown  nothing to go on, or the source itself hedges
*
* buffs         keyed by rule; status is the status effect id; abilities
*               grant it; duration in seconds; mainJob/subJob restrict
*               who it applies to
* conditional   requires names a buff; ceMain/ceSub add to CE by whether
*               job is main or support; percent scales the action's
*               enmity; transfer is the percent moved to the target
* gear          keyed by item id; subJob is the latent's condition
* avatarGear    keyed by item id; scales the avatar's enmity, not the wearer's
* effects       keyed by rule; what an ability does to its user's own
*               enmity: lowerMain/lowerSub take that percent of CE and VE
*               on the mob it's used on, by whether job is main or support;
*               setCe/setVe replace them on every mob within range yalms
* unquantified  documented enmity changes with no number to model
--]]

return {
    buffs = {
        -- "This ability gives +100 equipment enmity for its duration"
        -- "duration = 30 seconds"
        --   https://horizonffxi.wiki/Sentinel r116714
        sentinel = { status = 62, abilities = { 48 }, mainJob = 'PLD', enmity = 100, duration = 30, trust = 'era' },
        -- "Provides enmity +10."
        -- "base duration = 180 seconds"
        -- "decreases by 1 damage per successful hit.  The effect expires automatically when the damage reaches zero."
        --   https://horizonffxi.wiki/Enlight r113143
        enlight = { status = 274, spells = { 310 }, proc = 7, mainJob = 'PLD', enmity = 10, duration = 180, trust = 'era' },
        -- "+50 enmity if Paladin is subjob."
        --   https://horizonffxi.wiki/Sentinel r116714
        sentinelSub = { status = 62, abilities = { 48 }, subJob = 'PLD', enmity = 50, duration = 30, trust = 'unknown' },
        -- "increase enmity by 10"
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Yonin
        -- "duration = 5 minutes"
        -- "Cannot be used with Ninja as a support job."
        --   https://horizonffxi.wiki/Yonin r116637
        yonin = { status = 420, abilities = { 248 }, mainJob = 'NIN', enmity = 10, duration = 300, trust = 'era' },
        -- "Defender provides -25% enmity loss reduction when taking damage (works with WAR sub job)."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Defender
        -- "duration = 3 minutes"
        --   https://horizonffxi.wiki/Defender r26507
        defender = { status = 57, abilities = { 33 }, lossReduction = 25, duration = 180, trust = 'era' },
        -- "duration = 1 minute"
        -- "Each merit into Muted Soul will decrease the amount of enmity from, exclusively, Souleater damage by a -enmity value of 10."
        --   https://horizonffxi.wiki/Souleater r119987
        -- "if (PChar->StatusEffectContainer->HasStatusEffect(xi::StatusEffect::Souleater))"
        -- "enmityBonus -= PChar->PMeritPoints->GetMeritValue(xi::Merit::MutedSoul, PChar);"
        -- "float bonus = (100.0f + std::clamp(enmityBonus, -50, 100)) / 100.0f;"
        --   LandSandBoat src/map/enmity_container.cpp
        souleater = { status = 63, abilities = { 49 }, duration = 60, trust = 'era' },
    },
    conditional = {
        -- "Provoke now receives an additional 250 cumulative enmity (CE) when Defender is active and Warrior is set as the main job."
        -- "This number is reduced to +180 when Warrior is set as the support job."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Provoke
        provokeDefender = { abilities = { 35 }, requires = 'defender', job = 'WAR', ceMain = 250, ceSub = 180, trust = 'era' },
        -- "m_PSpell->getSpellFamily() == SPELLFAMILY_UTSUSEMI"
        -- "ce = 160; ve = 480;"
        --   LandSandBoat src/map/ai/states/magic_state.cpp
        utsusemiYonin = { spells = { 338, 339, 340 }, requires = 'yonin', ce = 160, ve = 480, trust = 'lsb' },
        -- "30% reduction in enmity gained from casting Enfeebling Magic while your main job is Red Mage."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767
        rdmEnfeebling = { mainJob = 'RDM', skill = 'enfeebling', percent = -30, trust = 'era' },
        -- "redirects 50% of the Thief's enmity to their chosen target"
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Collaborator
        collaborator = { abilities = { 236 }, transfer = 50, trust = 'era' },
    },
    gear = {
        -- "{{HorizonChangesBox|{{stat|Enmity|+5}} instead of {{stat|Enmity|+3}}"
        --   https://horizonffxi.wiki/Sattva_Ring r16997
        [15544] = { name = 'sattva_ring', enmity = 5, trust = 'era' },
        -- "{{stat|Latent Effect:}}<br>{{stat|Enmity|-2}}"
        -- "Active while White Mage is set as your Support Job."
        --   https://horizonffxi.wiki/Healer's_Earring r65412
        -- "VALUES (13437,27,-1,8,3);"
        --   LandSandBoat sql/item_latents.sql
        [13437] = { name = 'healers_earring', enmity = -2, subJob = 'WHM', trust = 'era' },
        -- "Mace Belt has been renamed to Healer's Belt, and its latent effect was changed from Club Skill +5 to Enmity -2."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767
        -- "VALUES (15273,90,5,8,3);"
        --   LandSandBoat sql/item_latents.sql
        [15273] = { name = 'mace_belt', enmity = -2, subJob = 'WHM', trust = 'era' },
    },
    avatarGear = {
        -- "{{stat|avatar}} {{stat|Enmity|-3}}"
        --   https://horizonffxi.wiki/Evoker's_Horn r104798
        [12520] = { name = 'evokers_horn', avatarEnmity = -3, trust = 'era' },
        -- "{{stat|avatar}} {{stat|Enmity|-2}}"
        --   https://horizonffxi.wiki/Evoker's_Doublet r16914
        [12650] = { name = 'evokers_doublet', avatarEnmity = -2, trust = 'era' },
        -- "{{stat|avatar}} {{stat|Enmity|-2}}"
        --   https://horizonffxi.wiki/Evoker's_Bracers r106935
        [13975] = { name = 'evokers_bracers', avatarEnmity = -2, trust = 'era' },
        -- "{{stat|avatar}} {{stat|Enmity|-2}}"
        --   https://horizonffxi.wiki/Evoker's_Pigaches r16927
        [14103] = { name = 'evokers_pigaches', avatarEnmity = -2, trust = 'era' },
        -- "'''[[Avatar]]:''' {{stat|Enmity|-3}}"
        --   https://horizonffxi.wiki/Evoker's_Horn_+1 r59164
        [15239] = { name = 'evokers_horn_+1', avatarEnmity = -3, trust = 'era' },
        -- "{{stat|Avatar}} {{stat|Enmity|-2}}"
        --   https://horizonffxi.wiki/Evoker's_Bracers_+1 r106934
        [14904] = { name = 'evokers_bracers_+1', avatarEnmity = -2, trust = 'era' },
        -- "{{stat|Avatar}} {{stat|Enmity|-4}}"
        --   https://horizonffxi.wiki/Evoker's_Pigaches_+1 r106724
        [15366] = { name = 'evokers_pigaches_+1', avatarEnmity = -4, trust = 'era' },
        -- "{{stat|Avatar}} {{stat|Enmity|+2}}"
        --   https://horizonffxi.wiki/Summoner's_Pigaches_+1 r113234
        [15679] = { name = 'summoners_pigaches_+1', avatarEnmity = 2, trust = 'era' },
        -- "{{stat|Avatar}}: {{stat|Enmity|+2}}"
        --   https://horizonffxi.wiki/Summoner's_Spats_+1 r71873
        [15594] = { name = 'summoners_spats_+1', avatarEnmity = 2, trust = 'era' },
    },
    effects = {
        -- "local enmityShed = 50"
        -- "if player:getMainJob() ~= xi.job.DRG then enmityShed = 30"
        -- "target:lowerEnmity(player, enmityShed + player:getMod(xi.mod.HIGH_JUMP_ENMITY_REDUCTION))"
        --   LandSandBoat scripts/globals/job_utils/dragoon.lua
        highJump = { abilities = { 67 }, job = 'DRG', lowerMain = 50, lowerSub = 30, trust = 'lsb' },
        -- "if mob:isMob() and mob:checkDistance(player) <= 75.0 then mob:setCE(player, 1) mob:setVE(player, 0)"
        --   LandSandBoat scripts/globals/job_utils/dragoon.lua
        superJump = { abilities = { 68 }, setCe = 1, setVe = 0, range = 75, trust = 'lsb' },
    },
    unquantified = {
        -- "reduced enmity generation, except on notorious monsters."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Magic Burst
        'magicBurst',
        -- "Camouflage grants an enmity reduction on the next attack."
        --   https://horizonffxi.wiki/Category:Horizon_Changes r123767, section Camouflage
        'camouflage',
    },
};
