--[[
* Copies Horizon's mob levels out of a mob taxonomy into
* addon/data/horizonlevels.lua, keyed by zone id and mob name.
*
*   luajit tools/genhorizonlevels.lua --taxonomy FILE [--lsb DIR] [--out FILE]
*
* Run from the repo root.  --taxonomy, or $ENMETRY_TAXONOMY, is a JSON file
* holding entries with zone, name, levelMin and levelMax, nested however it
* likes; it names zones the way the game does, and LandSandBoat's
* sql/zone_settings.sql (../LandSandBoat, $ENMETRY_LSB) turns those into zone
* ids.  A mob listed once per job, "Ul'aern (WAR)", is one entry under the
* name the game shows, spanning every variant's levels.  The header records a
* digest of the bytes read, so a regeneration says what it was built from.
--]]

package.path = './tools/?.lua;' .. package.path;

local bit = require('bit');
local json = require('json');
local emit = require('tables.emit');

local ZONES = 'sql/zone_settings.sql';

local function parseArgs(argv)
    local usage = 'usage: luajit tools/genhorizonlevels.lua --taxonomy FILE [--lsb DIR] [--out FILE]';
    local out = {
        taxonomy = os.getenv('ENMETRY_TAXONOMY'),
        lsb = os.getenv('ENMETRY_LSB') or '../LandSandBoat',
        out = 'addon/data/horizonlevels.lua',
    };
    local i = 1;
    while i <= #argv do
        local a = argv[i];
        if (a == '--taxonomy' or a == '--lsb' or a == '--out') and argv[i + 1] ~= nil then
            out[a:sub(3)] = argv[i + 1];
            i = i + 2;
        else
            error(usage);
        end
    end
    if out.taxonomy == nil then
        error(usage .. '\n       --taxonomy, or $ENMETRY_TAXONOMY, is required');
    end
    return out;
end

local function readFile(path)
    local fh = assert(io.open(path, 'rb'), 'cannot read ' .. path);
    local text = fh:read('*a');
    fh:close();
    return text;
end

-- FNV-1a over the source bytes, the prime applied as shifts so the 32-bit
-- product never leaves what a double holds exactly.
local function digest(text)
    local h = 2166136261;
    for i = 1, #text do
        h = bit.bxor(h, text:byte(i));
        h = bit.lshift(h, 1) + bit.lshift(h, 4) + bit.lshift(h, 7)
            + bit.lshift(h, 8) + bit.lshift(h, 24) + h;
    end
    return bit.tohex(h);
end

local function normalize(name)
    return name:lower():gsub('[^%w]', '');
end

-- Zone ids by normalized name, from zone_settings.sql.
local function zoneIds(lsb)
    local ids = {};
    for id, name in readFile(lsb .. '/' .. ZONES):gmatch("INSERT INTO `zone_settings` VALUES %((%d+),'[^']*',%d+,'([^']*)'") do
        ids[normalize(name)] = tonumber(id);
    end
    return ids;
end

-- The name the game shows: the taxonomy's job variants drop their " (JOB)" suffix.
local function shownName(name)
    return (name:gsub('%s*%(%u%u%u%)$', ''));
end

-- Every target entry with a zone, name and level range, wherever it sits.
local function collect(node, out)
    if type(node) ~= 'table' then
        return;
    end
    if node.zone ~= nil and node.name ~= nil and node.levelMin ~= nil and node.levelMax ~= nil then
        out[#out + 1] = node;
    end
    for _, v in pairs(node) do
        collect(v, out);
    end
end

local function build(taxonomy, ids)
    local zones = {};
    local names = {};
    local missing = {};
    local entries = {};
    collect(taxonomy, entries);
    for _, e in ipairs(entries) do
        local id = ids[normalize(e.zone)];
        if id == nil then
            missing[e.zone] = true;
        else
            names[id] = e.zone;
            local mobs = zones[id] or {};
            zones[id] = mobs;
            local name = shownName(e.name);
            local range = mobs[name];
            if range == nil then
                mobs[name] = { e.levelMin, e.levelMax };
            else
                range[1], range[2] = math.min(range[1], e.levelMin), math.max(range[2], e.levelMax);
            end
        end
    end
    local unmapped = {};
    for zone in pairs(missing) do
        unmapped[#unmapped + 1] = zone;
    end
    table.sort(unmapped);
    return zones, names, unmapped;
end

local function sortedKeys(t)
    local keys = {};
    for k in pairs(t) do
        keys[#keys + 1] = k;
    end
    table.sort(keys);
    return keys;
end

local function render(zones, names, source)
    local out = {
        emit.header({
            'GENERATED by tools/genhorizonlevels.lua; do not edit.',
            '',
            'Horizon mob level ranges by zone id and the name the game shows,',
            'copied from a Horizon mob taxonomy, ' .. source .. '.  A mob',
            'listed there once per job is one entry spanning every variant.',
            'Zone ids from LandSandBoat\'s ' .. ZONES .. '.',
        }),
        'return {',
    };
    for _, id in ipairs(sortedKeys(zones)) do
        out[#out + 1] = ('    [%d] = { -- %s'):format(id, names[id]);
        local mobs = zones[id];
        for _, name in ipairs(sortedKeys(mobs)) do
            out[#out + 1] = ('        [%s] = { %d, %d },'):format(emit.string(name), mobs[name][1], mobs[name][2]);
        end
        out[#out + 1] = '    },';
    end
    out[#out + 1] = '};';
    out[#out + 1] = '';
    return table.concat(out, '\n');
end

local function main(argv)
    local args = parseArgs(argv);
    local source = readFile(args.taxonomy);
    local zones, names, unmapped = build(json.decode(source), zoneIds(args.lsb));
    if #unmapped > 0 then
        error('zones with no id in zone_settings.sql: ' .. table.concat(unmapped, ', '));
    end
    local text = render(zones, names,
        ('digest %s over %d bytes'):format(digest(source), #source));
    local fh = assert(io.open(args.out, 'wb'), 'cannot write ' .. args.out);
    fh:write(text);
    fh:close();
    local count, mobs = 0, 0;
    for _, z in pairs(zones) do
        count = count + 1;
        for _ in pairs(z) do
            mobs = mobs + 1;
        end
    end
    print(('wrote %s: %d zones, %d mobs'):format(args.out, count, mobs));
end

main(arg);
