--[[
* Copies LandSandBoat's zone to region mapping into addon/data/regions.lua.
*
*   luajit tools/genregions.lua [--lsb DIR] [--out FILE]
*
* Run from the repo root.  LandSandBoat is found at ../LandSandBoat or
* $ENMETRY_LSB.  The mapping is the switch in zoneutils.cpp's
* GetCurrentRegion; zone numbers come from scripts/enum/zone.codegen.lua
* and region numbers from zone.h's REGION_TYPE.  Signet's resting bonus
* holds in regions up to Limbus and Sigil's in the Wings of the Goddess
* fronts, so the addon needs the region of the zone it is in.
--]]

package.path = './tools/?.lua;' .. package.path;

local emit = require('tables.emit');

local ZONES = 'scripts/enum/zone.codegen.lua';
local REGIONS = 'src/map/zone.h';
local SWITCH = 'src/map/utils/zoneutils.cpp';

local function parseArgs(argv)
    local out = { lsb = os.getenv('ENMETRY_LSB') or '../LandSandBoat', out = 'addon/data/regions.lua' };
    local i = 1;
    while i <= #argv do
        local a = argv[i];
        if (a == '--lsb' or a == '--out') and argv[i + 1] ~= nil then
            out[a:sub(3)] = argv[i + 1];
            i = i + 2;
        else
            error('usage: luajit tools/genregions.lua [--lsb DIR] [--out FILE]');
        end
    end
    return out;
end

local function readFile(path)
    local fh = assert(io.open(path, 'rb'), 'cannot read ' .. path);
    local text = fh:read('*a');
    fh:close();
    return text;
end

local function gitHead(dir)
    local fh = io.popen(('git -C "%s" log -1 --format=%%H%%x20%%ad --date=short 2>nul'):format(dir));
    local line = fh and fh:read('*l') or nil;
    if fh then
        fh:close();
    end
    return line or 'unknown';
end

-- SCREAMING_SNAKE and PascalCase meet here.
local function normalize(name)
    return name:lower():gsub('_', '');
end

local function enumValues(text)
    local out = {};
    for name, value in text:gmatch('\n%s*([%u%d_]+)%s*=%s*(%d+)') do
        out[normalize(name)] = tonumber(value);
        out['#' .. name] = tonumber(value);
    end
    return out;
end

local function build(lsb)
    local zones = enumValues(readFile(lsb .. '/' .. ZONES));
    local regions = enumValues(readFile(lsb .. '/' .. REGIONS));
    local body = readFile(lsb .. '/' .. SWITCH);
    local start = body:find('GetCurrentRegion%(const xi::ZoneId zoneId%) %-> REGION_TYPE');
    assert(start, 'GetCurrentRegion not found in ' .. SWITCH);
    local finish = body:find('\n}', start);
    local switch = body:sub(start, finish);

    local out, names, pending, missing = {}, {}, {}, {};
    for line in switch:gmatch('[^\n]+') do
        local zone = line:match('case xi::ZoneId::([%w_]+):');
        local region = line:match('return REGION_TYPE::([%w_]+);');
        if zone ~= nil then
            pending[#pending + 1] = zone;
        elseif region ~= nil then
            local id = regions[normalize(region)];
            assert(id ~= nil, 'unknown region ' .. region);
            for _, z in ipairs(pending) do
                local zoneId = zones[normalize(z)];
                if zoneId == nil then
                    missing[#missing + 1] = z;
                else
                    out[zoneId] = id;
                    names[zoneId] = z .. ' -> ' .. region;
                end
            end
            pending = {};
        end
    end
    return out, names, missing;
end

local function render(mapping, names, source)
    local ids = {};
    for id in pairs(mapping) do
        ids[#ids + 1] = id;
    end
    table.sort(ids);
    local out = {
        emit.header({
            'GENERATED by tools/genregions.lua; do not edit.',
            '',
            'Zone id -> region, as LandSandBoat\'s zoneutils.cpp GetCurrentRegion has',
            'it, at ' .. source .. '.  Region numbers are zone.h\'s REGION_TYPE:',
            'Signet\'s resting bonus holds up to 27 (Limbus), Sigil\'s in 33 to 40 (the',
            'Wings of the Goddess fronts).',
        }),
        'return {',
    };
    for _, id in ipairs(ids) do
        out[#out + 1] = ('    [%d] = %d, -- %s'):format(id, mapping[id], names[id]);
    end
    out[#out + 1] = '};';
    out[#out + 1] = '';
    return table.concat(out, '\n');
end

local function main(argv)
    local args = parseArgs(argv);
    local mapping, names, missing = build(args.lsb);
    if #missing > 0 then
        error('zones in the switch with no number: ' .. table.concat(missing, ', '));
    end
    local text = render(mapping, names, 'LandSandBoat ' .. gitHead(args.lsb));
    local fh = assert(io.open(args.out, 'wb'), 'cannot write ' .. args.out);
    fh:write(text);
    fh:close();
    local count = 0;
    for _ in pairs(mapping) do
        count = count + 1;
    end
    print(('wrote %s: %d zones'):format(args.out, count));
end

main(arg);
