--[[
* Regenerates every vendored enmity table under addon/data/.
*
*   luajit tools/gentables.lua                   from the pinned sources
*   luajit tools/gentables.lua --fetch-wiki      re-snapshot the wiki first
*   luajit tools/gentables.lua --lsb D:/LandSandBoat --out some/dir
*
* Run from the repo root.  Sources:
*
*   LandSandBoat at LSB_COMMIT, read from git objects, so the checkout can be
*   on any branch.  Found at ../LandSandBoat, $ENMETRY_LSB, or --lsb.
*
*   HorizonXI wiki snapshots in tools/tables/sources/horizonwiki/.
*
*   tools/tables/horizon.lua, the hand-curated rules.
--]]

package.path = './tools/?.lua;' .. package.path;

local actions   = require('tables.actions');
local cite      = require('tables.cite');
local emit      = require('tables.emit');
local horizon   = require('tables.horizon');
local lsb       = require('tables.lsb');
local moblevels = require('tables.moblevels');
local mobskills = require('tables.mobskills');
local overlays  = require('tables.overlays');
local snapshots = require('tables.snapshots');
local sql       = require('tables.sql');
local wiki      = require('tables.wiki');

-- The commit DESIGN.md's source line references were checked against.
local LSB_COMMIT = 'e81c8864748253105f9e6c36ab519c24eb01256f';

local ENMITY_TABLE = 'Enmity Table';

-- Era table spellings that differ from LSB's by more than punctuation.
local ALIASES = {
    ["Chocobo's Mazurka"] = 'chocobo_mazurka',
    ['Barthundara'] = 'barthundra',
    ['Dokuromi: Ichi'] = 'dokumori_ichi',
    ["Goddess's Hynmus"] = 'goddesss_hymnus',
    ["Maiden's Viralei"] = 'maidens_virelai',
};

local GENERATED = 'GENERATED by luajit tools/gentables.lua.  Do not edit; regenerate.';

local TRUST_LINES = {
    'Trust',
    '  era      measured in era (Kaeko), or documented as Horizon\'s own value',
    '  lsb      LandSandBoat\'s value with nothing to corroborate it',
    '  unknown  nothing to go on, or the source itself hedges',
};

local USAGE = 'usage: luajit tools/gentables.lua [--fetch-wiki] [--lsb DIR] [--out DIR]\n';

local function parseArgs(argv)
    local opts = {
        lsb = os.getenv('ENMETRY_LSB') or '../LandSandBoat',
        out = 'addon/data',
    };
    local i = 1;
    while i <= #argv do
        local a = argv[i];
        if a == '--fetch-wiki' then
            opts.fetch = true;
        elseif (a == '--lsb' or a == '--out') and argv[i + 1] ~= nil then
            opts[a:sub(3)] = argv[i + 1];
            i = i + 1;
        else
            io.stderr:write(USAGE);
            os.exit(2);
        end
        i = i + 1;
    end
    return opts;
end

-- A list of names as header lines, wrapped at 76 columns.
local function wrappedList(label, names)
    if #names == 0 then
        return { label .. ' none' };
    end
    local lines, line = {}, label;
    for i, name in ipairs(names) do
        local piece = name .. (i < #names and ',' or '');
        if #line + #piece + 1 > 76 then
            lines[#lines + 1] = line;
            line = '  ' .. piece;
        else
            line = line .. ' ' .. piece;
        end
    end
    lines[#lines + 1] = line;
    return lines;
end

local function append(list, more)
    for _, v in ipairs(more) do
        list[#list + 1] = v;
    end
    return list;
end

local function sortedKeys(t)
    local keys = {};
    for k in pairs(t) do
        keys[#keys + 1] = k;
    end
    table.sort(keys);
    return keys;
end

local function writeFile(path, text)
    local f = assert(io.open(path, 'wb'));
    f:write(text);
    f:close();
    print(('wrote %s (%d bytes)'):format(path, #text));
end

-- "ce/ve", with '-' for a value a source didn't give.
local function ceVe(pair)
    local function side(v) return v == nil and '-' or tostring(v); end
    return side(pair.ce) .. '/' .. side(pair.ve);
end

local function lsbSourceLine(src)
    return ('LandSandBoat %s (%s)'):format(src.lsb.commit, src.lsb.date);
end

local function citationComments(rule, pages, indent)
    local lines = {};
    for _, source in ipairs(rule.sources) do
        for _, quote in ipairs(source.quotes) do
            lines[#lines + 1] = ('%s-- "%s"'):format(indent, quote);
        end
        lines[#lines + 1] = ('%s--   %s'):format(indent, cite.describe(source, pages));
    end
    return lines;
end

local function filesUnder(repo, dir, pattern)
    local paths = {};
    for _, p in ipairs(repo:list(dir)) do
        if p:match(pattern) then
            paths[#paths + 1] = p;
        end
    end
    return paths;
end

local function baseName(path)
    return path:match('([^/]+)%.lua$');
end

--[[ actions.lua ]]

local ACTION_FIELDS = { 'name', 'ce', 've', 'ceTrust', 'veTrust', 'lsbCe', 'lsbVe', 'perTarget', 'cure' };

local function renderActions(built, src)
    local era = src.pages[ENMITY_TABLE];
    local header = append({
        GENERATED,
        '',
        'Base CE/VE for every job ability and spell, before the Enmity bonus,',
        'and the fixed CE/VE of the weaponskills that generate it in place of',
        'their damage\'s.  Keyed by LandSandBoat ability, spell and weaponskill id.',
        '',
        'Sources',
        '  lsb      ' .. lsbSourceLine(src),
        '           sql/abilities.sql, sql/spell_list.sql, sql/weapon_skills.sql,',
        '           the updateEnmityFromCure calls in scripts/actions and',
        '           job_utils, and params.overrideCE/VE in scripts/actions/weaponskills',
        ('  era      %s r%d (%s)'):format(era.url, era.revision, era.timestamp),
        '           Kaeko\'s testing; the page warns VE is only accurate to +/-10',
        '  horizon  tools/tables/horizon.lua; each delta\'s quoted source is above it',
        '',
    }, TRUST_LINES);
    append(header, {
        '',
        'Fields',
        '  ce, ve            the base values; trust is per value',
        '  perTarget         the era value is per target hit (Multiple Targets)',
        '  cure = formula    also generates cure enmity from HP healed',
        '  cure = fixed      ce/ve are the whole cure enmity, whatever is healed',
        '',
        'weaponskills holds only those with an override: a hit that lands adds',
        'ce/ve, scaled by Enmity, instead of the damage formula (weaponskills.lua',
        'addEnmity).  A weaponskill absent from it generates enmity from damage.',
        ('%d weaponskill scripts scanned.'):format(built.weaponskillScripts),
        '',
        'Each entry\'s trailing comment gives the values each source had.',
        '',
    });
    append(header, wrappedList('Era rows matching no ability or spell:', built.unmatched));
    append(header, wrappedList('Era rows matching several:', built.ambiguous));
    append(header, wrappedList('Era rows too malformed to read:', built.malformed));

    local out = { emit.header(header), 'return {' };
    for _, kind in ipairs({ 'abilities', 'spells', 'weaponskills' }) do
        out[#out + 1] = ('    %s = {'):format(kind);
        for _, id in ipairs(sortedKeys(built[kind])) do
            local e = built[kind][id];
            local notes = {};
            if e.delta ~= nil then
                append(out, citationComments(e.delta, src.pages, '        '));
                notes[#notes + 1] = 'horizon ' .. ceVe(e.delta);
            end
            if e.era ~= nil then
                notes[#notes + 1] = ('era %s %s'):format(emit.string(e.wiki), ceVe(e.era));
            end
            notes[#notes + 1] = 'lsb ' .. ceVe(e.lsb);
            out[#out + 1] = ('        [%d] = %s, -- %s'):format(id, emit.inline(e, ACTION_FIELDS), table.concat(notes, '; '));
        end
        out[#out + 1] = '    },';
    end

    out[#out + 1] = '    -- Constants from the era table\'s Misc. Actions.';
    out[#out + 1] = '    misc = {';
    for _, key in ipairs(sortedKeys(built.misc)) do
        local m = built.misc[key];
        out[#out + 1] = ('        %s = %s, -- era %s'):format(key, emit.inline(m, { 'ce', 've', 'trust' }), emit.string(m.wiki));
    end
    out[#out + 1] = '    },';
    out[#out + 1] = '};\n';
    return table.concat(out, '\n');
end

--[[ mobskills.lua ]]

local function renderMobskills(built, src)
    local header = {
        GENERATED,
        '',
        'What mob TP moves do to the hate list of the player they hit.',
        '',
        'Sources',
        '  lsb  ' .. lsbSourceLine(src),
        '       sql/mob_skills.sql, the script each id names in',
        '       scripts/actions/mobskills, and scripts/zones/*/mobs',
        '',
        'skills  keyed by mobskill id, the param of a category 11 action packet',
        '        (mobskill_state.cpp); the trailing comment is file:line',
        '  effect = reset    mob:resetEnmity(target): CE and VE both zeroed',
        '  effect = reduce   mob:lowerEnmity(target, percent): both lowered by percent',
        '  effect = none     no effect on the hit player\'s enmity',
        '  conditional       the call sits under a condition, usually "if it landed"',
        '  trust = unknown   the script makes some other enmity call, or a mob',
        '                    script resets on this skill; named in the comment',
        '  An id absent from skills has no script and is a gap, not a none.',
        '',
        'mobs    [zone id][mob name] for mobs whose own script resets or lowers',
        '        enmity, on a skill, a timer or a hit.  Their switches are not',
        '        explained by skills alone.',
        '',
        ('%d ids from %d scripts; %d script names in mob_skills.sql have no file.'):format(
            built.count, built.scripts, #built.missing),
        '',
    };
    append(header, wrappedList('Mob script zones with no data/zones directory:', built.unzoned));

    local out = { emit.header(header), 'return {', '    skills = {' };
    for _, id in ipairs(sortedKeys(built.skills)) do
        local s = built.skills[id];
        local where = s.name .. '.lua' .. (s.line and (':' .. s.line) or '');
        if s.call ~= nil then
            where = where .. ' ' .. s.call;
        end
        out[#out + 1] = ('        [%d] = %s, -- %s'):format(id,
            emit.inline(s, { 'name', 'effect', 'percent', 'conditional', 'trust' }), where);
    end
    out[#out + 1] = '    },';
    out[#out + 1] = '    mobs = {';
    for _, zone in ipairs(sortedKeys(built.mobs)) do
        local z = built.mobs[zone];
        out[#out + 1] = ('        [%d] = { -- scripts/zones/%s/mobs'):format(zone, z.dir);
        for _, m in ipairs(z.mobs) do
            local skills = #m.skills > 0 and (', checks skills ' .. table.concat(m.skills, ' ')) or '';
            out[#out + 1] = ('            [%s] = true, -- %s.lua:%d%s'):format(emit.string(m.name), m.file, m.line, skills);
        end
        out[#out + 1] = '        },';
    end
    out[#out + 1] = '    },';
    out[#out + 1] = '};\n';
    return table.concat(out, '\n');
end

--[[ moblevels.lua ]]

local function renderMoblevels(levels, src)
    local header = {
        GENERATED,
        '',
        'Mob level ranges, from which a mob\'s exact level is sampled.',
        '',
        'Keyed by zone id.  Each zone is one flat array of runs sorted by index,',
        'four numbers a run, one run a line:',
        '  firstIndex, lastIndex, minLevel, maxLevel',
        'where index is the low 12 bits of the server id',
        '(0x01000000 | zone << 12 | index).  Indices in no run have no level.',
        'Flat so the whole table is a few hundred Lua tables, not tens of',
        'thousands.  Read it through tables.levelRange.',
        '',
        'Sources',
        '  lsb  ' .. lsbSourceLine(src),
        '       the spawns: section of data/zones/<zone>/mobs.yaml, named per zone',
        '',
        ('%d spawns have no level in the YAML: scripted spawns, levelled by the'):format(levels.levelless),
        'script that spawns them.  They are in no run.',
        '',
    };
    append(header, wrappedList('Spawns left out for a zero or inverted range:', levels.rejected));

    local out = { emit.header(header), 'return {' };
    for _, zone in ipairs(sortedKeys(levels.zones)) do
        local z = levels.zones[zone];
        out[#out + 1] = ('    [%d] = { -- %s, %d spawns'):format(zone, z.path, z.spawns);
        for _, run in ipairs(z.runs) do
            out[#out + 1] = ('        %d, %d, %d, %d,'):format(run[1], run[2], run[3], run[4]);
        end
        out[#out + 1] = '    },';
    end
    out[#out + 1] = '};\n';
    return table.concat(out, '\n');
end

--[[ overlays.lua ]]

local function renderOverlays(resolved, src)
    local header = append({
        GENERATED,
        '',
        'Enmity rules that aren\'t a single action\'s base value: buffs,',
        'conditional bonuses, and gear.  Curated in tools/tables/horizon.lua;',
        'every rule is preceded by the quotes that justify it and where they',
        'are, checked against the sources at generation.',
        '',
        'Sources',
        '  lsb      ' .. lsbSourceLine(src),
        '  horizon  HorizonXI wiki snapshots at the revisions cited',
        '',
    }, TRUST_LINES);
    append(header, {
        '',
        'buffs         keyed by rule; status is the status effect id; abilities',
        '              grant it; duration in seconds; mainJob/subJob restrict',
        '              who it applies to',
        'conditional   requires names a buff; ceMain/ceSub add to CE by whether',
        '              job is main or support; percent scales the action\'s',
        '              enmity; transfer is the percent moved to the target',
        'gear          keyed by item id; subJob is the latent\'s condition',
        'avatarGear    keyed by item id; scales the avatar\'s enmity, not the wearer\'s',
        'effects       keyed by rule; what an ability does to its user\'s own',
        '              enmity: lowerMain/lowerSub take that percent of CE and VE',
        '              on the mob it\'s used on, by whether job is main or support;',
        '              setCe/setVe replace them on every mob within range yalms',
        'unquantified  documented enmity changes with no number to model',
    });

    local out = { emit.header(header), 'return {' };
    for _, section in ipairs(overlays.SECTIONS) do
        out[#out + 1] = ('    %s = {'):format(section.name);
        local fields = overlays.fields(section.name);
        for _, r in ipairs(resolved[section.name]) do
            append(out, citationComments(r.source, src.pages, '        '));
            if section.name == 'unquantified' then
                out[#out + 1] = ('        %s,'):format(emit.string(r.key));
            else
                local key = type(r.key) == 'number' and ('[%d]'):format(r.key) or r.key;
                out[#out + 1] = ('        %s = %s,'):format(key, emit.inline(r, fields));
            end
        end
        out[#out + 1] = '    },';
    end
    out[#out + 1] = '};\n';
    return table.concat(out, '\n');
end

--[[ building ]]

local function buildActions(src, paths)
    local helpers = {};
    for _, p in ipairs(paths.jobUtils) do
        append(helpers, actions.cureFunctions(src.files[p]));
    end
    local cures = { spells = {}, abilities = {} };
    for kind, list in pairs({ spells = paths.spells, abilities = paths.abilities }) do
        for _, p in ipairs(list) do
            cures[kind][baseName(p)] = actions.cure(src.files[p], helpers);
        end
    end

    local overrides = {};
    for _, p in ipairs(paths.weaponskills) do
        overrides[baseName(p)] = actions.weaponskillOverride(src.files[p]);
    end

    for _, group in ipairs({ 'actions', 'fixedCures' }) do
        for _, rule in ipairs(horizon[group]) do
            cite.verify(rule, src.pages, src.files);
        end
    end
    local built = actions.build({
        abilities = sql.rows(src.files['sql/abilities.sql'], 'abilities'),
        spells = sql.rows(src.files['sql/spell_list.sql'], 'spell_list'),
        cures = cures,
        fixedByEra = horizon.fixedCures[1].names,
        era = wiki.enmityTable(src.pages[ENMITY_TABLE].text),
        aliases = ALIASES,
        deltas = horizon.actions,
        weaponskills = sql.rows(src.files['sql/weapon_skills.sql'], 'weapon_skills'),
        overrides = overrides,
    });
    built.weaponskillScripts = #paths.weaponskills;
    return built;
end

local function buildLevels(src, paths)
    local levels = { zones = {}, rejected = {}, levelless = 0, dirs = {} };
    for _, p in ipairs(paths.zones) do
        local spawns, invalid, levelless = moblevels.spawns(src.files[p]);
        levels.levelless = levels.levelless + levelless;
        for _, s in ipairs(invalid) do
            levels.rejected[#levels.rejected + 1] = ('%d [%d, %d]'):format(s.id, s.min, s.max);
        end
        for zone, runs in pairs(moblevels.runs(spawns)) do
            if levels.zones[zone] ~= nil then
                error(('zone %d has spawns in both %s and %s'):format(zone, levels.zones[zone].path, p), 0);
            end
            local count = 0;
            for _, s in ipairs(spawns) do
                if moblevels.zone(s.id) == zone then
                    count = count + 1;
                end
            end
            levels.zones[zone] = { path = p, runs = runs, spawns = count };
            levels.dirs[p:match('^data/zones/([^/]+)/'):lower()] = zone;
        end
    end
    return levels;
end

local function buildMobskills(src, paths, levels)
    local scripts = {};
    for _, p in ipairs(paths.mobskills) do
        scripts[baseName(p)] = src.files[p];
    end
    local built = mobskills.build(sql.rows(src.files['sql/mob_skills.sql'], 'mob_skills'), scripts);
    built.count = #sortedKeys(built.skills);
    built.scripts = #paths.mobskills;

    local enum = mobskills.skillEnum(src.files['scripts/enum/mob_skill.lua']);
    built.mobs, built.unzoned = {}, {};
    local found, unzoned = {}, {};
    for _, p in ipairs(paths.mobScripts) do
        local dir, file = p:match('^scripts/zones/([^/]+)/mobs/([^/]+)%.lua$');
        local m = mobskills.mobScript(src.files[p], enum);
        if m ~= nil then
            m.mob, m.file, m.name = dir .. '/' .. file, file, file:gsub('_', ' ');
            found[#found + 1] = m;
            local zone = levels.dirs[dir:lower()];
            if zone == nil then
                if not unzoned[dir] then
                    unzoned[dir] = true;
                    built.unzoned[#built.unzoned + 1] = dir;
                end
            else
                built.mobs[zone] = built.mobs[zone] or { dir = dir, mobs = {} };
                table.insert(built.mobs[zone].mobs, m);
            end
        end
    end
    mobskills.applyMobScripts(built, found);
    return built;
end

local function main(argv)
    local opts = parseArgs(argv);
    -- The era table is itself cited, by horizon.fixedCures.
    local titles, lsbPaths = overlays.sources(horizon);
    if opts.fetch then
        snapshots.fetch(titles);
    end

    local repo, err = lsb.open(opts.lsb, LSB_COMMIT);
    if repo == nil then
        io.stderr:write(err .. '\nclone LandSandBoat and pass --lsb, or set ENMETRY_LSB\n');
        os.exit(1);
    end

    local paths = {
        mobskills = filesUnder(repo, 'scripts/actions/mobskills', '%.lua$'),
        spells = filesUnder(repo, 'scripts/actions/spells', '%.lua$'),
        abilities = filesUnder(repo, 'scripts/actions/abilities', '%.lua$'),
        weaponskills = filesUnder(repo, 'scripts/actions/weaponskills', '%.lua$'),
        jobUtils = filesUnder(repo, 'scripts/globals/job_utils', '%.lua$'),
        mobScripts = filesUnder(repo, 'scripts/zones', '^scripts/zones/[^/]+/mobs/[^/]+%.lua$'),
        zones = filesUnder(repo, 'data/zones', '/mobs%.yaml$'),
    };

    -- Every LSB file, read in one batch.
    local wanted = append({
        'sql/abilities.sql', 'sql/spell_list.sql', 'sql/weapon_skills.sql', 'sql/mob_skills.sql', 'sql/item_basic.sql',
        'data/status_effects.yaml', 'scripts/enum/mob_skill.lua',
    }, lsbPaths);
    for _, list in pairs(paths) do
        append(wanted, list);
    end
    table.sort(wanted);

    local src = {
        lsb = repo,
        files = repo:read(wanted),
        pages = snapshots.load(titles),
    };

    local builtActions = buildActions(src, paths);
    local levels = buildLevels(src, paths);
    local builtSkills = buildMobskills(src, paths, levels);
    local resolved = overlays.resolve(horizon, {
        pages = src.pages,
        files = src.files,
        actions = builtActions,
        statusIds = overlays.statusIds(src.files['data/status_effects.yaml']),
        itemNames = overlays.itemNames(src.files['sql/item_basic.sql']),
    });

    local dir = opts.out:gsub('[/\\]$', '');
    writeFile(dir .. '/actions.lua', renderActions(builtActions, src));
    writeFile(dir .. '/mobskills.lua', renderMobskills(builtSkills, src));
    writeFile(dir .. '/moblevels.lua', renderMoblevels(levels, src));
    writeFile(dir .. '/overlays.lua', renderOverlays(resolved, src));
end

main(arg);
